### ISSUE TITLE
Support for new HLF version Raft and metrics collection

### ISSUE THREAD

**Issue by aakzubaidi** [JulianD267/Hyperledger-Fabric2-0-configurator#1]
Hi, 

Very nice tool and well-composed. I think Every researcher and learner as well will find your tool very appealing to use. It is well documented as well. Just wondering if there is a plan to support new HLF structure and Raft as well as support for metrics collection. I am willing to collaborate on this as I find your tool very interesting.

Regards, 

Ali Alzubaidi

**Comment by JulianD267** [comment]
Hi Ali,
thank you for your kind message! I'm glad that the tool helps you with your research/learning. Currently this tool is not being actively maintained but rather on a spontaneous basis, due to lack of spare time and other research focusses. Though, indeed i am planning to incorporate the Raft Ordering Service into it, thereby exchanging the now deprecated Kafka Service (might take some time though). Regarding Metrics collection and other aspects, there is nothing planned. I'd love to see you forking the project and maybe implement those features if you so desire. For that, i am always willing to collaborate with you and share my experiences with you.
If you are further interested in my research which was aided by this tool, you may have a look at my paper:
"Performance analysis of hyperledger fabric 2.0 blockchain platform." [Here](https://doi.org/10.1145/3417310.3431398)
Additionally, there is one coming up focussing on the optimal configuration of HLF Business frameworks. 
Regards,,
Julian Dreyer

**Comment by aakzubaidi** [comment]
Thanks, Julian. Actually, I got to know your tool from your paper. Interesting paper BTW. I have been digging into recent Fabric Samples which composes 2 org, 1 peer for each and one Raft orderer. I succeeded to understand a huge portion of its files, structure, bash scripts, yaml, and so on. I edited it to compose a proper fabric network of 2 orgs or two peers and 5 orderers. But I think your tool is more flexible, especially for benchmarking. So, yes, I will be looking into your tool and how does work. Also, I am looking forward to meeting you online at any time at your convenience and discuss that more.

**Comment by JulianD267** [comment]
Great to hear that! You can always contact me via the E-Mail provided in the header of the Paper. Great news hearing that you got that to work! In theory my tool should allow an easy exchange of the kafka ordering service for raft. Though, i am currently struggling with the TLS portion, which is required by Raft and has not been a huge focus of the tool. Let me know if there are any advances on your side.

**Comment by aakzubaidi** [comment]
Yes, I understand that it can cumbersome to handle the CA part and, MSP crypto materials, and registration process. I sent you a set of files that I hope to help you see you a fine-grained way to bring a CA authority and generate the MSP and everything needed for that. I will then be looking forward to seeing how you will take from there.

**Comment by JulianD267** [comment]
Issue should be resolved, added Raft and TLS Support within commit ea23538
